version: '3.8'

services:
  
  data:
    image: postgres
    container_name: data_base
    ports:  
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - pgdata:/data/postgres.env
    

volumes:
  pgdata:
    driver: local